image: jangrewe/gitlab-ci-android

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - cat app/src/main/assets/*.xml | grep "<level " | cut -d '"' -f 2 | sort -g | uniq --repeated | wc -l | xargs test 0 -eq
  - ./gradlew assembleDebug
