name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Check duplicated level IDs
        run: cat app/src/main/assets/*.xml | grep "<level " | cut -d '"' -f 2 | sort -g | uniq --repeated | wc -l | xargs test 0 -eq
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build app
        run: ./gradlew assembleDebug
